/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListAllTokenIds200ResponseAccessTokenIdArrayInner } from '../models/ListAllTokenIds200ResponseAccessTokenIdArrayInner';
import { HttpFile } from '../http/http';

export class AccessTokenIdListResponse {
    /**
    * Name of the object.
    */
    'object': string;
    /**
    * Array of access tokens Id.
    */
    'accessTokenIdArray': Array<ListAllTokenIds200ResponseAccessTokenIdArrayInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "accessTokenIdArray",
            "baseName": "AccessTokenIdArray",
            "type": "Array<ListAllTokenIds200ResponseAccessTokenIdArrayInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccessTokenIdListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

