/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AdditionalLevels1 {
    'object': string;
    'level1': string | null;
    'level2': string | null;
    'level3': string | null;
    'level4': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "level1",
            "baseName": "level1",
            "type": "string",
            "format": ""
        },
        {
            "name": "level2",
            "baseName": "level2",
            "type": "string",
            "format": ""
        },
        {
            "name": "level3",
            "baseName": "level3",
            "type": "string",
            "format": ""
        },
        {
            "name": "level4",
            "baseName": "level4",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AdditionalLevels1.attributeTypeMap;
    }

    public constructor() {
    }
}

