/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetCase200ResponsePartiesPartyArrayInnerContact } from '../models/GetCase200ResponsePartiesPartyArrayInnerContact';
import { HttpFile } from '../http/http';

export class AssociatedSoSPerson1 {
    'object': string;
    'contact': GetCase200ResponsePartiesPartyArrayInnerContact;
    'entityName': string;
    'entityType': AssociatedSoSPerson1EntityTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "contact",
            "baseName": "contact",
            "type": "GetCase200ResponsePartiesPartyArrayInnerContact",
            "format": ""
        },
        {
            "name": "entityName",
            "baseName": "entityName",
            "type": "string",
            "format": ""
        },
        {
            "name": "entityType",
            "baseName": "entityType",
            "type": "AssociatedSoSPerson1EntityTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssociatedSoSPerson1.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AssociatedSoSPerson1EntityTypeEnum {
    Partner = 'Partner',
    Agent = 'Agent',
    Ceo = 'CEO',
    PartnerGeneralMember = 'Partner/General Member',
    PartnerGeneralMember2 = 'Partner/GeneralMember'
}

