/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BarRecordPreview1 } from '../models/BarRecordPreview1';
import { CaseTimeline1 } from '../models/CaseTimeline1';
import { HttpFile } from '../http/http';

export class AssociatedNormAttorney {
    'object': string;
    /**
    * Link to details for the Attorney.
    */
    'normAttorneyAPI': string;
    'normAttorneyId': string;
    'caseTimeline': CaseTimeline1;
    'name': string;
    'firstName': string;
    'middleName': string | null;
    'lastName': string;
    /**
    * Link to related cases for this association.
    */
    'caseSearchAPI': string;
    'caseCount': number;
    'stateBarDataArray': Array<BarRecordPreview1>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "normAttorneyAPI",
            "baseName": "normAttorneyAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "normAttorneyId",
            "baseName": "normAttorneyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseTimeline",
            "baseName": "caseTimeline",
            "type": "CaseTimeline1",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "middleName",
            "baseName": "middleName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseSearchAPI",
            "baseName": "caseSearchAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCount",
            "baseName": "caseCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "stateBarDataArray",
            "baseName": "stateBarDataArray",
            "type": "Array<BarRecordPreview1>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssociatedNormAttorney.attributeTypeMap;
    }

    public constructor() {
    }
}

