/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BarSourceData1PublicHearingArrayInner {
    'conduct': string | null;
    'date': Date | null;
    'issuedBy': string | null;
    'order': string | null;
    'respondent': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conduct",
            "baseName": "conduct",
            "type": "string",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "issuedBy",
            "baseName": "issuedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "string",
            "format": ""
        },
        {
            "name": "respondent",
            "baseName": "respondent",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BarSourceData1PublicHearingArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

