/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BarSourceData1DisciplinaryHistoryArrayInner {
    'action': string | null;
    'caseNumber': string | null;
    'complaint': string | null;
    'contactId': string | null;
    'dateOfAction': Date | null;
    'definition': string | null;
    'disciplinaryDecision': string | null;
    'entryDate': Date | null;
    'information': string | null;
    'link': string | null;
    'note': string | null;
    'probationDate': Date | null;
    'reinstatedDate': Date | null;
    'rule': string | null;
    'ruleNumber': string | null;
    'sectionDate': Date | null;
    'status': string | null;
    'stayDate': Date | null;
    'supremeCourt': string | null;
    'term': string | null;
    'typeOfAction': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseNumber",
            "baseName": "caseNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "complaint",
            "baseName": "complaint",
            "type": "string",
            "format": ""
        },
        {
            "name": "contactId",
            "baseName": "contactId",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateOfAction",
            "baseName": "dateOfAction",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "definition",
            "baseName": "definition",
            "type": "string",
            "format": ""
        },
        {
            "name": "disciplinaryDecision",
            "baseName": "disciplinaryDecision",
            "type": "string",
            "format": ""
        },
        {
            "name": "entryDate",
            "baseName": "entryDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "information",
            "baseName": "information",
            "type": "string",
            "format": ""
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "probationDate",
            "baseName": "probationDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "reinstatedDate",
            "baseName": "reinstatedDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "rule",
            "baseName": "rule",
            "type": "string",
            "format": ""
        },
        {
            "name": "ruleNumber",
            "baseName": "ruleNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "sectionDate",
            "baseName": "sectionDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "stayDate",
            "baseName": "stayDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "supremeCourt",
            "baseName": "supremeCourt",
            "type": "string",
            "format": ""
        },
        {
            "name": "term",
            "baseName": "term",
            "type": "string",
            "format": ""
        },
        {
            "name": "typeOfAction",
            "baseName": "typeOfAction",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BarSourceData1DisciplinaryHistoryArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

