/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BarSourceData1FeesOptionsArrayInner {
    'contingencyFees': string | null;
    'flatFees': string | null;
    'hourlyRate': string | null;
    'paymentPlans': string | null;
    'slidingScaleFees': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contingencyFees",
            "baseName": "contingencyFees",
            "type": "string",
            "format": ""
        },
        {
            "name": "flatFees",
            "baseName": "flatFees",
            "type": "string",
            "format": ""
        },
        {
            "name": "hourlyRate",
            "baseName": "hourlyRate",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentPlans",
            "baseName": "paymentPlans",
            "type": "string",
            "format": ""
        },
        {
            "name": "slidingScaleFees",
            "baseName": "slidingScaleFees",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BarSourceData1FeesOptionsArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

