/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetBillingUsageByBillingCycle200ResponseApiCallsBillable } from '../models/GetBillingUsageByBillingCycle200ResponseApiCallsBillable';
import { GetBillingUsageByBillingCycle200ResponseApiCallsCredited } from '../models/GetBillingUsageByBillingCycle200ResponseApiCallsCredited';
import { GetBillingUsageByBillingCycle200ResponseApiCallsMade } from '../models/GetBillingUsageByBillingCycle200ResponseApiCallsMade';
import { GetBillingUsageByBillingCycle200ResponseBillingCycle } from '../models/GetBillingUsageByBillingCycle200ResponseBillingCycle';
import { HttpFile } from '../http/http';

export class BillingCycleUsageResponse {
    /**
    * Name of the object.
    */
    'object': string;
    'billingCycle': GetBillingUsageByBillingCycle200ResponseBillingCycle;
    /**
    * Billing cycle days.
    */
    'days': any;
    /**
    * Billing cycle apiUsage.
    */
    'apiUsage': any;
    'apiCallsMade': GetBillingUsageByBillingCycle200ResponseApiCallsMade;
    'apiCallsCredited': GetBillingUsageByBillingCycle200ResponseApiCallsCredited;
    'apiCallsBillable': GetBillingUsageByBillingCycle200ResponseApiCallsBillable;
    /**
    * Total number of successful case tracks.
    */
    'totalCasesTracked': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingCycle",
            "baseName": "billingCycle",
            "type": "GetBillingUsageByBillingCycle200ResponseBillingCycle",
            "format": ""
        },
        {
            "name": "days",
            "baseName": "days",
            "type": "any",
            "format": ""
        },
        {
            "name": "apiUsage",
            "baseName": "apiUsage",
            "type": "any",
            "format": ""
        },
        {
            "name": "apiCallsMade",
            "baseName": "apiCallsMade",
            "type": "GetBillingUsageByBillingCycle200ResponseApiCallsMade",
            "format": ""
        },
        {
            "name": "apiCallsCredited",
            "baseName": "apiCallsCredited",
            "type": "GetBillingUsageByBillingCycle200ResponseApiCallsCredited",
            "format": ""
        },
        {
            "name": "apiCallsBillable",
            "baseName": "apiCallsBillable",
            "type": "GetBillingUsageByBillingCycle200ResponseApiCallsBillable",
            "format": ""
        },
        {
            "name": "totalCasesTracked",
            "baseName": "totalCasesTracked",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BillingCycleUsageResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

