/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CaseCountAnalyticsByCaseFiledDate1 {
    'object': string;
    'caseCount': number;
    /**
    * Link to cases for this criteria.
    */
    'caseSearchAPI': string;
    'groupedBy': CaseCountAnalyticsByCaseFiledDate1GroupedByEnum;
    'year': number;
    'quarter': CaseCountAnalyticsByCaseFiledDate1QuarterEnum | null;
    'monthString': CaseCountAnalyticsByCaseFiledDate1MonthStringEnum | null;
    'monthInt': number | null;
    'weekOfYear': number | null;
    'weekOfMonth': number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseCount",
            "baseName": "caseCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "caseSearchAPI",
            "baseName": "caseSearchAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "groupedBy",
            "baseName": "groupedBy",
            "type": "CaseCountAnalyticsByCaseFiledDate1GroupedByEnum",
            "format": ""
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number",
            "format": ""
        },
        {
            "name": "quarter",
            "baseName": "quarter",
            "type": "CaseCountAnalyticsByCaseFiledDate1QuarterEnum",
            "format": ""
        },
        {
            "name": "monthString",
            "baseName": "monthString",
            "type": "CaseCountAnalyticsByCaseFiledDate1MonthStringEnum",
            "format": ""
        },
        {
            "name": "monthInt",
            "baseName": "monthInt",
            "type": "number",
            "format": ""
        },
        {
            "name": "weekOfYear",
            "baseName": "weekOfYear",
            "type": "number",
            "format": ""
        },
        {
            "name": "weekOfMonth",
            "baseName": "weekOfMonth",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CaseCountAnalyticsByCaseFiledDate1.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CaseCountAnalyticsByCaseFiledDate1GroupedByEnum {
    Yearly = 'Yearly',
    Quarterly = 'Quarterly',
    Monthly = 'Monthly',
    Weekly = 'Weekly'
}
export enum CaseCountAnalyticsByCaseFiledDate1QuarterEnum {
    Q1 = 'Q1',
    Q2 = 'Q2',
    Q3 = 'Q3',
    Q4 = 'Q4',
    Null = 'null'
}
export enum CaseCountAnalyticsByCaseFiledDate1MonthStringEnum {
    January = 'January',
    February = 'February',
    March = 'March',
    April = 'April',
    May = 'May',
    June = 'June',
    July = 'July',
    August = 'August',
    September = 'September',
    October = 'October',
    November = 'November',
    December = 'December',
    Null = 'null'
}

