/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CaseUpdatePacerOptionsResponse1 } from '../models/CaseUpdatePacerOptionsResponse1';
import { Exception1 } from '../models/Exception1';
import { GetCase200Response } from '../models/GetCase200Response';
import { HttpFile } from '../http/http';

export class CaseUpdate {
    /**
    * Name of the object.
    */
    'object': string;
    /**
    * Unique Id for a Case in UniCourt.
    */
    'caseId': string;
    /**
    * Status of the request.
    */
    'status': CaseUpdateStatusEnum;
    /**
    * The date and time when the case was last requested for update 
    */
    'requestedDate': Date;
    'caseAPI': string;
    'pacerOptions': CaseUpdatePacerOptionsResponse1 | null;
    'exception': Exception1 | null;
    '_case': GetCase200Response | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseId",
            "baseName": "caseId",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CaseUpdateStatusEnum",
            "format": ""
        },
        {
            "name": "requestedDate",
            "baseName": "requestedDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "caseAPI",
            "baseName": "caseAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "pacerOptions",
            "baseName": "pacerOptions",
            "type": "CaseUpdatePacerOptionsResponse1",
            "format": ""
        },
        {
            "name": "exception",
            "baseName": "exception",
            "type": "Exception1",
            "format": ""
        },
        {
            "name": "_case",
            "baseName": "case",
            "type": "GetCase200Response",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CaseUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CaseUpdateStatusEnum {
    Complete = 'COMPLETE',
    Failure = 'FAILURE',
    InProgress = 'IN_PROGRESS'
}

