/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Exception1 } from '../models/Exception1';
import { ExportFile1 } from '../models/ExportFile1';
import { GetCase200ResponseDocketEntriesDocketEntryArrayInnerDocketEntryPrimaryDocumentsCaseDocumentArrayInner } from '../models/GetCase200ResponseDocketEntriesDocketEntryArrayInnerDocketEntryPrimaryDocumentsCaseDocumentArrayInner';
import { HttpFile } from '../http/http';

export class CaseDocumentOrderCallback {
    /**
    * Name of the object.
    */
    'object': string;
    /**
    * Unique Id for the Case Document Order Callback.
    */
    'caseDocumentOrderCallbackId': string;
    /**
    * UniCourt\'s Case Document ID.
    */
    'caseDocumentId': string;
    /**
    * Date when the job is run.
    */
    'callbackGeneratedDate': Date | null;
    /**
    * Status of the request.
    */
    'status': CaseDocumentOrderCallbackStatusEnum;
    'caseDocument': GetCase200ResponseDocketEntriesDocketEntryArrayInnerDocketEntryPrimaryDocumentsCaseDocumentArrayInner | null;
    'caseDocumentOrderCallbackAPI': string;
    'file': ExportFile1 | null;
    'exception': Exception1 | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseDocumentOrderCallbackId",
            "baseName": "caseDocumentOrderCallbackId",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseDocumentId",
            "baseName": "caseDocumentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "callbackGeneratedDate",
            "baseName": "callbackGeneratedDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CaseDocumentOrderCallbackStatusEnum",
            "format": ""
        },
        {
            "name": "caseDocument",
            "baseName": "caseDocument",
            "type": "GetCase200ResponseDocketEntriesDocketEntryArrayInnerDocketEntryPrimaryDocumentsCaseDocumentArrayInner",
            "format": ""
        },
        {
            "name": "caseDocumentOrderCallbackAPI",
            "baseName": "caseDocumentOrderCallbackAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "ExportFile1",
            "format": ""
        },
        {
            "name": "exception",
            "baseName": "exception",
            "type": "Exception1",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CaseDocumentOrderCallback.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CaseDocumentOrderCallbackStatusEnum {
    Complete = 'COMPLETE',
    Failure = 'FAILURE',
    InProgress = 'IN_PROGRESS',
    Delayed = 'DELAYED'
}

