/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Provides Court Data per State Jurisdiction for an entity.
*/
export class CaseAnalyticsAPI {
    'object': string;
    'caseCountAnalyticsByCourtAPI': string;
    'caseCountAnalyticsByCourtTypeAPI': string;
    'caseCountAnalyticsByCourtSystemAPI': string;
    'caseCountAnalyticsByCourtLocationAPI': string;
    'caseCountAnalyticsByJurisdictionGeoAPI': string;
    'caseCountAnalyticsByAreaOfLawAPI': string;
    'caseCountAnalyticsByCaseClassAPI': string;
    'caseCountAnalyticsByCaseTypeAPI': string;
    'caseCountAnalyticsByCaseTypeGroupAPI': string;
    'caseCountAnalyticsByPartyRoleAPI': string | null;
    'caseCountAnalyticsByPartyRoleGroupAPI': string | null;
    'totalCases': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseCountAnalyticsByCourtAPI",
            "baseName": "caseCountAnalyticsByCourtAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByCourtTypeAPI",
            "baseName": "caseCountAnalyticsByCourtTypeAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByCourtSystemAPI",
            "baseName": "caseCountAnalyticsByCourtSystemAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByCourtLocationAPI",
            "baseName": "caseCountAnalyticsByCourtLocationAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByJurisdictionGeoAPI",
            "baseName": "caseCountAnalyticsByJurisdictionGeoAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByAreaOfLawAPI",
            "baseName": "caseCountAnalyticsByAreaOfLawAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByCaseClassAPI",
            "baseName": "caseCountAnalyticsByCaseClassAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByCaseTypeAPI",
            "baseName": "caseCountAnalyticsByCaseTypeAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByCaseTypeGroupAPI",
            "baseName": "caseCountAnalyticsByCaseTypeGroupAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByPartyRoleAPI",
            "baseName": "caseCountAnalyticsByPartyRoleAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByPartyRoleGroupAPI",
            "baseName": "caseCountAnalyticsByPartyRoleGroupAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "totalCases",
            "baseName": "totalCases",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CaseAnalyticsAPI.attributeTypeMap;
    }

    public constructor() {
    }
}

