/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CaseStatus1 {
    'object': string;
    'caseStatusId': string;
    'caseStatusGroupId': string;
    'caseStatusGroup': string;
    'name': string | null;
    'caseClassArray': Array<string> | null;
    /**
    * The date and time when it was first created. This date and time is in UTC. Formatted as YYYY-MM-DD HH:MM:SS.
    */
    'createdDate': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseStatusId",
            "baseName": "caseStatusId",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseStatusGroupId",
            "baseName": "caseStatusGroupId",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseStatusGroup",
            "baseName": "caseStatusGroup",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseClassArray",
            "baseName": "caseClassArray",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return CaseStatus1.attributeTypeMap;
    }

    public constructor() {
    }
}

