/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetCase200ResponsePartiesPartyArrayInnerContactAddressArrayInner } from '../models/GetCase200ResponsePartiesPartyArrayInnerContactAddressArrayInner';
import { GetCase200ResponsePartiesPartyArrayInnerContactEmailArrayInner } from '../models/GetCase200ResponsePartiesPartyArrayInnerContactEmailArrayInner';
import { GetCase200ResponsePartiesPartyArrayInnerContactPhoneNumberArrayInner } from '../models/GetCase200ResponsePartiesPartyArrayInnerContactPhoneNumberArrayInner';
import { HttpFile } from '../http/http';

/**
* Contact object data schema.
*/
export class Contact {
    'object': string;
    /**
    * List of available addresses.
    */
    'addressArray': Array<GetCase200ResponsePartiesPartyArrayInnerContactAddressArrayInner> | null;
    /**
    * List of available phone numbers.
    */
    'phoneNumberArray': Array<GetCase200ResponsePartiesPartyArrayInnerContactPhoneNumberArrayInner> | null;
    /**
    * List of available emails.
    */
    'emailArray': Array<GetCase200ResponsePartiesPartyArrayInnerContactEmailArrayInner> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressArray",
            "baseName": "addressArray",
            "type": "Array<GetCase200ResponsePartiesPartyArrayInnerContactAddressArrayInner>",
            "format": ""
        },
        {
            "name": "phoneNumberArray",
            "baseName": "phoneNumberArray",
            "type": "Array<GetCase200ResponsePartiesPartyArrayInnerContactPhoneNumberArrayInner>",
            "format": ""
        },
        {
            "name": "emailArray",
            "baseName": "emailArray",
            "type": "Array<GetCase200ResponsePartiesPartyArrayInnerContactEmailArrayInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Contact.attributeTypeMap;
    }

    public constructor() {
    }
}

