/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Court1 } from '../models/Court1';
import { GetCourtCoverage200ResponseCaseClassCoverageArrayInner } from '../models/GetCourtCoverage200ResponseCaseClassCoverageArrayInner';
import { HttpFile } from '../http/http';

export class CourtCoverage {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * Date when it was last updated.
    */
    'lastUpdateCountDate': string;
    'court': Court1 | null;
    /**
    * Total Cases for a specific court.
    */
    'totalCaseCount': number;
    /**
    * Total Cases in last 30 days that were added to UniCourt
    */
    'totalCasesInLastThirtyDaysCount': number;
    /**
    * Total Free Case Documents for a specific court.
    */
    'totalFreeCaseDocumentCount': number;
    /**
    * Total Free Case Documents in last 30 days that were added to UniCourt
    */
    'totalFreeCaseDocumentsInLastThirtyDaysCount': number;
    /**
    * Total Paid Case Documents for a specific court.
    */
    'totalPaidCaseDocumentCount': number;
    /**
    * Total Paid Case Documents in last 30 days that were added to UniCourt
    */
    'totalPaidCaseDocumentsInLastThirtyDaysCount': number;
    /**
    * Count of total Case Documents added in UniCourt Library.
    */
    'totalCaseDocumentInLibraryCount': number;
    /**
    * Count of total Case Documents added in UniCourt Library in last 30 days
    */
    'totalCaseDocumentInLibraryInLastThirtyDaysCount': number;
    'caseClassCoverageArray': Array<GetCourtCoverage200ResponseCaseClassCoverageArrayInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastUpdateCountDate",
            "baseName": "lastUpdateCountDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "court",
            "baseName": "court",
            "type": "Court1",
            "format": ""
        },
        {
            "name": "totalCaseCount",
            "baseName": "totalCaseCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalCasesInLastThirtyDaysCount",
            "baseName": "totalCasesInLastThirtyDaysCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalFreeCaseDocumentCount",
            "baseName": "totalFreeCaseDocumentCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalFreeCaseDocumentsInLastThirtyDaysCount",
            "baseName": "totalFreeCaseDocumentsInLastThirtyDaysCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalPaidCaseDocumentCount",
            "baseName": "totalPaidCaseDocumentCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalPaidCaseDocumentsInLastThirtyDaysCount",
            "baseName": "totalPaidCaseDocumentsInLastThirtyDaysCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalCaseDocumentInLibraryCount",
            "baseName": "totalCaseDocumentInLibraryCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalCaseDocumentInLibraryInLastThirtyDaysCount",
            "baseName": "totalCaseDocumentInLibraryInLastThirtyDaysCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "caseClassCoverageArray",
            "baseName": "caseClassCoverageArray",
            "type": "Array<GetCourtCoverage200ResponseCaseClassCoverageArrayInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CourtCoverage.attributeTypeMap;
    }

    public constructor() {
    }
}

