/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CourtLocation1 {
    'object': string;
    'courtLocationId': string;
    'name': string;
    /**
    * 1st part of the street address.
    */
    'streetAddress1': string | null;
    /**
    * 2nd part of the street address.
    */
    'streetAddress2': string | null;
    /**
    * City
    */
    'city': string | null;
    /**
    * State Name if present else default value.
    */
    'stateName': string;
    /**
    * The date and time when it was first created. This date and time is in UTC. Formatted as YYYY-MM-DD HH:MM:SS.
    */
    'createdDate': Date;
    'courtsForCourtLocationAPI': string;
    'courtServiceStatusAPI': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "courtLocationId",
            "baseName": "courtLocationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "streetAddress1",
            "baseName": "streetAddress1",
            "type": "string",
            "format": ""
        },
        {
            "name": "streetAddress2",
            "baseName": "streetAddress2",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string",
            "format": ""
        },
        {
            "name": "stateName",
            "baseName": "stateName",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "courtsForCourtLocationAPI",
            "baseName": "courtsForCourtLocationAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "courtServiceStatusAPI",
            "baseName": "courtServiceStatusAPI",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return CourtLocation1.attributeTypeMap;
    }

    public constructor() {
    }
}

