/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetBillingUsageByBillingCycle200ResponseApiCallsBillable } from '../models/GetBillingUsageByBillingCycle200ResponseApiCallsBillable';
import { GetBillingUsageByBillingCycle200ResponseApiCallsCredited } from '../models/GetBillingUsageByBillingCycle200ResponseApiCallsCredited';
import { GetBillingUsageByBillingCycle200ResponseApiCallsMade } from '../models/GetBillingUsageByBillingCycle200ResponseApiCallsMade';
import { HttpFile } from '../http/http';

export class DailyUsageResponse {
    /**
    * Name of the object.
    */
    'object': string;
    /**
    * Start time of the usage.
    */
    'usageStartTime': Date;
    /**
    * End time of the usage.
    */
    'usageEndTime': Date;
    /**
    * Api Usage made in real time.
    */
    'apiUsage': any;
    'apiCallsMade': GetBillingUsageByBillingCycle200ResponseApiCallsMade;
    'apiCallsCredited': GetBillingUsageByBillingCycle200ResponseApiCallsCredited;
    'apiCallsBillable': GetBillingUsageByBillingCycle200ResponseApiCallsBillable;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "usageStartTime",
            "baseName": "usageStartTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "usageEndTime",
            "baseName": "usageEndTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "apiUsage",
            "baseName": "apiUsage",
            "type": "any",
            "format": ""
        },
        {
            "name": "apiCallsMade",
            "baseName": "apiCallsMade",
            "type": "GetBillingUsageByBillingCycle200ResponseApiCallsMade",
            "format": ""
        },
        {
            "name": "apiCallsCredited",
            "baseName": "apiCallsCredited",
            "type": "GetBillingUsageByBillingCycle200ResponseApiCallsCredited",
            "format": ""
        },
        {
            "name": "apiCallsBillable",
            "baseName": "apiCallsBillable",
            "type": "GetBillingUsageByBillingCycle200ResponseApiCallsBillable",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DailyUsageResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

