/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Exception1 } from '../models/Exception1';
import { HttpFile } from '../http/http';

export class DocumentDownload {
    /**
    * Name of the object.
    */
    'object': string;
    /**
    * Requested Document ID.
    */
    'caseDocumentId': string;
    /**
    * Expiry date-time for the fileUrl provided in this object.
    */
    'expiryDate': string | null;
    /**
    * Link to download the file.
    */
    'fileUrl': string | null;
    /**
    * API call to download the document again if the above fileUrl is expired.
    */
    'caseDocumentDownloadAPI': string | null;
    'exception': Exception1 | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseDocumentId",
            "baseName": "caseDocumentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiryDate",
            "baseName": "expiryDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileUrl",
            "baseName": "fileUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseDocumentDownloadAPI",
            "baseName": "caseDocumentDownloadAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "exception",
            "baseName": "exception",
            "type": "Exception1",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentDownload.attributeTypeMap;
    }

    public constructor() {
    }
}

