/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Nature Of Suit for a case.
*/
export class GetCase200ResponseSourceCaseDataNatureOfSuitArrayInner {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * Source nos code data from the court site.
    */
    'sourceText': string | null;
    /**
    * Nos Code from the source site which is extracted from the sourceText.
    */
    'code': number;
    /**
    * Code Name from the source site which is extracted from the sourceText.
    */
    'name': string | null;
    /**
    * Section of a nos code extracted from the sourceText.
    */
    'section': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceText",
            "baseName": "sourceText",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "section",
            "baseName": "section",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCase200ResponseSourceCaseDataNatureOfSuitArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

