/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetCallbacks200ResponseCaseDocumentOrderCallbacks } from '../models/GetCallbacks200ResponseCaseDocumentOrderCallbacks';
import { GetCallbacks200ResponseCaseExportCallbacks } from '../models/GetCallbacks200ResponseCaseExportCallbacks';
import { HttpFile } from '../http/http';

export class GetCallbacks200Response {
    /**
    * Name of the object.
    */
    'object': string;
    'caseDocumentOrderCallbacks': GetCallbacks200ResponseCaseDocumentOrderCallbacks;
    'caseExportCallbacks': GetCallbacks200ResponseCaseExportCallbacks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseDocumentOrderCallbacks",
            "baseName": "caseDocumentOrderCallbacks",
            "type": "GetCallbacks200ResponseCaseDocumentOrderCallbacks",
            "format": ""
        },
        {
            "name": "caseExportCallbacks",
            "baseName": "caseExportCallbacks",
            "type": "GetCallbacks200ResponseCaseExportCallbacks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCallbacks200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

