/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderCaseDocument200Response } from '../models/OrderCaseDocument200Response';
import { HttpFile } from '../http/http';

export class GetCaseDocumentOrderCallbacks200Response {
    /**
    * Name of the object.
    */
    'object': string;
    /**
    * Total number of pages available.
    */
    'totalPages': number;
    /**
    * Total number of case document order callback objects available.
    */
    'totalCount': number;
    /**
    * Current page number.
    */
    'pageNumber': number;
    /**
    * Link for the next page.
    */
    'nextPageAPI': string | null;
    /**
    * Link for the previous page.
    */
    'previousPageAPI': string | null;
    /**
    * Array of case document order callback objects.
    */
    'callbackArray': Array<OrderCaseDocument200Response>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalPages",
            "baseName": "totalPages",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "pageNumber",
            "baseName": "pageNumber",
            "type": "number",
            "format": ""
        },
        {
            "name": "nextPageAPI",
            "baseName": "nextPageAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "previousPageAPI",
            "baseName": "previousPageAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "callbackArray",
            "baseName": "callbackArray",
            "type": "Array<OrderCaseDocument200Response>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCaseDocumentOrderCallbacks200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

