/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CaseClass1 } from '../models/CaseClass1';
import { HttpFile } from '../http/http';

export class GetCourtCoverage200ResponseCaseClassCoverageArrayInner {
    /**
    * Name of the object
    */
    'object': string;
    'caseClass': CaseClass1;
    /**
    * API Link to the Court Service status with filters of court and case class
    */
    'courtServiceStatusAPI': string;
    /**
    * Total Cases for a specific CourtLocation.
    */
    'caseCount': number;
    /**
    * Cases in last 30 days that were added to UniCourt for a specific CourtLocation
    */
    'casesInLastThirtyDaysCount': number;
    /**
    * Free Case Documents for a specific CourtLocation.
    */
    'freeCaseDocumentCount': number;
    /**
    * Free Case Documents in last 30 days that were added to UniCourt for a specific CourtLocation.
    */
    'freeCaseDocumentsInLastThirtyDaysCount': number;
    /**
    * Paid Case Documents for a specific CourtLocation.
    */
    'paidCaseDocumentCount': number;
    /**
    * Paid Case Documents in last 30 days that were added to UniCourt for a specific CourtLocation.
    */
    'paidCaseDocumentsInLastThirtyDaysCount': number;
    /**
    * Case Documents that were added to UniCourt Crowd Source Library for a specific CourtLocationy.
    */
    'caseDocumentInLibraryCount': number;
    /**
    * Case Documents that were added to UniCourt Crowd Source Library for a specific CourtLocation in last 30 days.
    */
    'caseDocumentInLibraryInLastThirtyDaysCount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseClass",
            "baseName": "caseClass",
            "type": "CaseClass1",
            "format": ""
        },
        {
            "name": "courtServiceStatusAPI",
            "baseName": "courtServiceStatusAPI",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseCount",
            "baseName": "caseCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "casesInLastThirtyDaysCount",
            "baseName": "casesInLastThirtyDaysCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "freeCaseDocumentCount",
            "baseName": "freeCaseDocumentCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "freeCaseDocumentsInLastThirtyDaysCount",
            "baseName": "freeCaseDocumentsInLastThirtyDaysCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "paidCaseDocumentCount",
            "baseName": "paidCaseDocumentCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "paidCaseDocumentsInLastThirtyDaysCount",
            "baseName": "paidCaseDocumentsInLastThirtyDaysCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "caseDocumentInLibraryCount",
            "baseName": "caseDocumentInLibraryCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "caseDocumentInLibraryInLastThirtyDaysCount",
            "baseName": "caseDocumentInLibraryInLastThirtyDaysCount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCourtCoverage200ResponseCaseClassCoverageArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

