/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CaseTrackPostRequestLastTrackedDetails } from '../models/CaseTrackPostRequestLastTrackedDetails';
import { CaseUpdatePacerOptionsResponse1 } from '../models/CaseUpdatePacerOptionsResponse1';
import { Schedule2 } from '../models/Schedule2';
import { HttpFile } from '../http/http';

export class GetCaseTracks200ResponseCaseTrackPreviewArrayInner {
    /**
    * Name of the object.
    */
    'object': string;
    /**
    * Unique Id for a Case in UniCourt.
    */
    'caseId': string;
    'pacerOptions': CaseUpdatePacerOptionsResponse1 | null;
    'schedule': Schedule2;
    'lastTrackedDetails': CaseTrackPostRequestLastTrackedDetails | null;
    /**
    * The date and time when the case was last fetched from the Court. This date and time is in UTC. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz, Note: It is not necessary that every time the case is fetched from Court we find changes in the case information. It could be that we already have the latest information from the Court and no changes exist.
    */
    'lastFetchDate': Date | null;
    /**
    * The date and time when the case was last fetched from the Court where we found changes in the case information. This date and time is in UTC. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz,
    */
    'lastFetchDateWithUpdates': Date | null;
    'caseAPI': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseId",
            "baseName": "caseId",
            "type": "string",
            "format": ""
        },
        {
            "name": "pacerOptions",
            "baseName": "pacerOptions",
            "type": "CaseUpdatePacerOptionsResponse1",
            "format": ""
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "Schedule2",
            "format": ""
        },
        {
            "name": "lastTrackedDetails",
            "baseName": "lastTrackedDetails",
            "type": "CaseTrackPostRequestLastTrackedDetails",
            "format": ""
        },
        {
            "name": "lastFetchDate",
            "baseName": "lastFetchDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastFetchDateWithUpdates",
            "baseName": "lastFetchDateWithUpdates",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "caseAPI",
            "baseName": "caseAPI",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return GetCaseTracks200ResponseCaseTrackPreviewArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

