/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CaseStatus1 } from '../models/CaseStatus1';
import { CaseType1 } from '../models/CaseType1';
import { Court1 } from '../models/Court1';
import { CourtLocation1 } from '../models/CourtLocation1';
import { GetCase200ResponseAttorneys } from '../models/GetCase200ResponseAttorneys';
import { GetCase200ResponseCaseDocuments } from '../models/GetCase200ResponseCaseDocuments';
import { GetCase200ResponseCaseStats } from '../models/GetCase200ResponseCaseStats';
import { GetCase200ResponseCauseOfActionArrayInner } from '../models/GetCase200ResponseCauseOfActionArrayInner';
import { GetCase200ResponseChargeArrayInner } from '../models/GetCase200ResponseChargeArrayInner';
import { GetCase200ResponseDocketEntries } from '../models/GetCase200ResponseDocketEntries';
import { GetCase200ResponseHearings } from '../models/GetCase200ResponseHearings';
import { GetCase200ResponseJudges } from '../models/GetCase200ResponseJudges';
import { GetCase200ResponseParties } from '../models/GetCase200ResponseParties';
import { GetCase200ResponseRelatedCases } from '../models/GetCase200ResponseRelatedCases';
import { GetCase200ResponseSourceCaseData } from '../models/GetCase200ResponseSourceCaseData';
import { HttpFile } from '../http/http';

export class GetCase200Response {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * Unique identifier of Case.
    */
    'caseId': string;
    /**
    * URL to the case page in UniCourt Application.
    */
    'url': string | null;
    /**
    * Case number as provided by Court.
    */
    'caseNumber': string;
    /**
    * Case name as provided by Court.
    */
    'caseName': string | null;
    /**
    * Filing date for the case provided by the Court. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz
    */
    'filedDate': Date;
    /**
    * This field determines if this case object has only meta information. If the value is true and if the full information is required you would need to call the updateCase API.
    */
    'hasOnlyMetaInfo': boolean;
    /**
    * Court Service Status ID of the requested case where we can use it to get the service status
    */
    'courtServiceStatusId': string | null;
    /**
    * API to get the service statuses of the given case.
    */
    'courtServiceStatusAPI': string | null;
    'court': Court1 | null;
    'courtLocation': CourtLocation1 | null;
    'caseType': CaseType1 | null;
    /**
    * Array of charges that are added to this case.
    */
    'chargeArray': Array<GetCase200ResponseChargeArrayInner>;
    'caseStatus': CaseStatus1 | null;
    /**
    * Array of cause of Actions that are added to this case.
    */
    'causeOfActionArray': Array<GetCase200ResponseCauseOfActionArrayInner>;
    /**
    * The date and time when the case was first fetched from the Court. This date and time is in UTC. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz,.
    */
    'firstFetchDate': Date;
    /**
    * The date and time when the case was last fetched from the Court. This date and time is in UTC. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz, Note: It is not necessary that every time the case is fetched from Court we find changes in the case information. It could be that we already have the latest information from the Court and no changes exist.
    */
    'lastFetchDate': Date;
    /**
    * The date and time when the case was last fetched from the Court where we found changes in the case information. This date and time is in UTC. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz,
    */
    'lastFetchDateWithUpdates': Date;
    /**
    * The date and time when parties/attorneys were last updated from the Court. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz, Note: This is currently applicable for Federal PACER cases since we have an option to exclude parties and fetch only latest docket entries when updating cases to save PACER fees.
    */
    'participantsLastFetchDate': Date | null;
    /**
    * The status of source data of case. If the value of sourceDataStatus is SOURCE_DEPRECATED then it means that the Case has been migrated from old court site to a new court site and the data being shown in the API response is from a old court site. If the sourceDataStatus is NO_LONGER_AVAILABLE_IN_COURT then it means that a particular case is invalid in the court site.
    */
    'sourceDataStatus': GetCase200ResponseSourceDataStatusEnum | null;
    'sourceCaseData': GetCase200ResponseSourceCaseData;
    /**
    * This field will be set to TRUE if atleast one document has a preview.
    */
    'hasDocumentsWithPreview': boolean;
    /**
    * When a case is beyond the threshold of entities we provide this link so that the user can request and get all the data of the case with one additional call. This data will be zipped and sent via a webhoook.
    */
    'exportAPI': string;
    'caseStats': GetCase200ResponseCaseStats;
    'parties': GetCase200ResponseParties | null;
    'attorneys': GetCase200ResponseAttorneys | null;
    'judges': GetCase200ResponseJudges | null;
    'docketEntries': GetCase200ResponseDocketEntries | null;
    'hearings': GetCase200ResponseHearings | null;
    'caseDocuments': GetCase200ResponseCaseDocuments | null;
    'relatedCases': GetCase200ResponseRelatedCases | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseId",
            "baseName": "caseId",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseNumber",
            "baseName": "caseNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseName",
            "baseName": "caseName",
            "type": "string",
            "format": ""
        },
        {
            "name": "filedDate",
            "baseName": "filedDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "hasOnlyMetaInfo",
            "baseName": "hasOnlyMetaInfo",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "courtServiceStatusId",
            "baseName": "courtServiceStatusId",
            "type": "string",
            "format": ""
        },
        {
            "name": "courtServiceStatusAPI",
            "baseName": "courtServiceStatusAPI",
            "type": "string",
            "format": ""
        },
        {
            "name": "court",
            "baseName": "court",
            "type": "Court1",
            "format": ""
        },
        {
            "name": "courtLocation",
            "baseName": "courtLocation",
            "type": "CourtLocation1",
            "format": ""
        },
        {
            "name": "caseType",
            "baseName": "caseType",
            "type": "CaseType1",
            "format": ""
        },
        {
            "name": "chargeArray",
            "baseName": "chargeArray",
            "type": "Array<GetCase200ResponseChargeArrayInner>",
            "format": ""
        },
        {
            "name": "caseStatus",
            "baseName": "caseStatus",
            "type": "CaseStatus1",
            "format": ""
        },
        {
            "name": "causeOfActionArray",
            "baseName": "causeOfActionArray",
            "type": "Array<GetCase200ResponseCauseOfActionArrayInner>",
            "format": ""
        },
        {
            "name": "firstFetchDate",
            "baseName": "firstFetchDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastFetchDate",
            "baseName": "lastFetchDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastFetchDateWithUpdates",
            "baseName": "lastFetchDateWithUpdates",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "participantsLastFetchDate",
            "baseName": "participantsLastFetchDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "sourceDataStatus",
            "baseName": "sourceDataStatus",
            "type": "GetCase200ResponseSourceDataStatusEnum",
            "format": ""
        },
        {
            "name": "sourceCaseData",
            "baseName": "sourceCaseData",
            "type": "GetCase200ResponseSourceCaseData",
            "format": ""
        },
        {
            "name": "hasDocumentsWithPreview",
            "baseName": "hasDocumentsWithPreview",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "exportAPI",
            "baseName": "exportAPI",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseStats",
            "baseName": "caseStats",
            "type": "GetCase200ResponseCaseStats",
            "format": ""
        },
        {
            "name": "parties",
            "baseName": "parties",
            "type": "GetCase200ResponseParties",
            "format": ""
        },
        {
            "name": "attorneys",
            "baseName": "attorneys",
            "type": "GetCase200ResponseAttorneys",
            "format": ""
        },
        {
            "name": "judges",
            "baseName": "judges",
            "type": "GetCase200ResponseJudges",
            "format": ""
        },
        {
            "name": "docketEntries",
            "baseName": "docketEntries",
            "type": "GetCase200ResponseDocketEntries",
            "format": ""
        },
        {
            "name": "hearings",
            "baseName": "hearings",
            "type": "GetCase200ResponseHearings",
            "format": ""
        },
        {
            "name": "caseDocuments",
            "baseName": "caseDocuments",
            "type": "GetCase200ResponseCaseDocuments",
            "format": ""
        },
        {
            "name": "relatedCases",
            "baseName": "relatedCases",
            "type": "GetCase200ResponseRelatedCases",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCase200Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GetCase200ResponseSourceDataStatusEnum {
    NoLongerAvailableInCourt = 'NO_LONGER_AVAILABLE_IN_COURT',
    SourceDeprecated = 'SOURCE_DEPRECATED',
    Null = 'null'
}

