/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Contact object Data Schema.
*/
export class GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceDataRawOrderedDataArrayInnerChildArrayInnerChildArrayInner {
    /**
    * Label of the docket from the source.
    */
    'lbl': string | null;
    /**
    * Structure order.
    */
    'ord': number;
    /**
    * List of available addresses.
    */
    'val': string | null;
    'childArray': Array<any>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lbl",
            "baseName": "lbl",
            "type": "string",
            "format": ""
        },
        {
            "name": "ord",
            "baseName": "ord",
            "type": "number",
            "format": ""
        },
        {
            "name": "val",
            "baseName": "val",
            "type": "string",
            "format": ""
        },
        {
            "name": "childArray",
            "baseName": "childArray",
            "type": "Array<any>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceDataRawOrderedDataArrayInnerChildArrayInnerChildArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

