/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Object consisiting of each docket entry number and its corresponding API call.
*/
export class GetCase200ResponseDocketEntriesDocketEntryArrayInnerReferencedDocketNumberArrayInner {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * Each referenced docket number
    */
    'docketNumber': number;
    /**
    * Link to Docket Entries API with the current docket number. The response of this API will give all the primary documents and secondary documents that are associated to it.
    */
    'docketEntriesAPI': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "docketNumber",
            "baseName": "docketNumber",
            "type": "number",
            "format": ""
        },
        {
            "name": "docketEntriesAPI",
            "baseName": "docketEntriesAPI",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCase200ResponseDocketEntriesDocketEntryArrayInnerReferencedDocketNumberArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

