/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Name of the attorney\'s law firm as provided by Court. This can be null as some Courts do not provide this as a separate field.
*/
export class GetCase200ResponseAttorneysAttorneyArrayInnerAttorneyLawFirmArrayInner {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * ID for the law firm of an attorney in this case. This ID is unique within a case and NOT across cases. If the same attorney were to appear in another case this ID would be different.
    */
    'attorneyLawFirmId': string | null;
    /**
    * Name of the law firm as provided by Court.
    */
    'name': string;
    /**
    * Signifies if the attorney as this attorney type is currently isVisible or not for the case.
    */
    'isVisible': boolean;
    /**
    * Is the date when the document was first fetched from the court site.
    */
    'firstFetchDate': string;
    /**
    * Is the date when the document was last fetched from the court site.
    */
    'lastFetchDate': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "attorneyLawFirmId",
            "baseName": "attorneyLawFirmId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "isVisible",
            "baseName": "isVisible",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "firstFetchDate",
            "baseName": "firstFetchDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastFetchDate",
            "baseName": "lastFetchDate",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCase200ResponseAttorneysAttorneyArrayInnerAttorneyLawFirmArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

