/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetCase200ResponsePartiesPartyArrayInnerPartyAttorneyAssociationsPartyAttorneyAssociationArrayInner {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * ID of the association
    */
    'partyAttorneyAssociationId': string;
    /**
    * ID for the attorney in this case. This ID is unique within a case and NOT across cases. If the same attorney were to appear in another case this ID would be different.
    */
    'attorneyId': string;
    /**
    * ID for the party in this case. This ID is unique within a case and NOT across cases. If the same attorney were to appear in another case this ID would be different.
    */
    'partyId': string;
    /**
    * Signifies if this party attorney relationship is currently isVisible or not for the case.
    */
    'isVisible': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "partyAttorneyAssociationId",
            "baseName": "partyAttorneyAssociationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "attorneyId",
            "baseName": "attorneyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "partyId",
            "baseName": "partyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "isVisible",
            "baseName": "isVisible",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCase200ResponsePartiesPartyArrayInnerPartyAttorneyAssociationsPartyAttorneyAssociationArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

