/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetCase200ResponseSourceCaseDataNatureOfSuitArrayInner } from '../models/GetCase200ResponseSourceCaseDataNatureOfSuitArrayInner';
import { GetCase200ResponseSourceCaseDataSourceCauseOfActionArrayInner } from '../models/GetCase200ResponseSourceCaseDataSourceCauseOfActionArrayInner';
import { GetCase200ResponseSourceCaseDataSourceChargeArrayInner } from '../models/GetCase200ResponseSourceCaseDataSourceChargeArrayInner';
import { GetCase200ResponseSourceCaseDataSourcePageDataInner } from '../models/GetCase200ResponseSourceCaseDataSourcePageDataInner';
import { HttpFile } from '../http/http';

/**
* Source data in the court website.
*/
export class GetCase200ResponseSourceCaseData {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * Courtrhouse as provided by Court.
    */
    'sourceCourt': string;
    /**
    * Case Type for a case which is provided by the Court.
    */
    'sourceCaseType': string;
    /**
    * Array of Charges for a case which is provided by the Court.
    */
    'sourceChargeArray': Array<GetCase200ResponseSourceCaseDataSourceChargeArrayInner>;
    /**
    * Array of Charges for a case which is provided by the Court.
    */
    'natureOfSuitArray': Array<GetCase200ResponseSourceCaseDataNatureOfSuitArrayInner>;
    /**
    * Array of Cause Of Action for a case which is provided by the Court.
    */
    'sourceCauseOfActionArray': Array<GetCase200ResponseSourceCaseDataSourceCauseOfActionArrayInner>;
    /**
    * Case Status as provided by Court.
    */
    'sourceCaseStatus': string;
    'sourcePageData': Array<GetCase200ResponseSourceCaseDataSourcePageDataInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceCourt",
            "baseName": "sourceCourt",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceCaseType",
            "baseName": "sourceCaseType",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceChargeArray",
            "baseName": "sourceChargeArray",
            "type": "Array<GetCase200ResponseSourceCaseDataSourceChargeArrayInner>",
            "format": ""
        },
        {
            "name": "natureOfSuitArray",
            "baseName": "natureOfSuitArray",
            "type": "Array<GetCase200ResponseSourceCaseDataNatureOfSuitArrayInner>",
            "format": ""
        },
        {
            "name": "sourceCauseOfActionArray",
            "baseName": "sourceCauseOfActionArray",
            "type": "Array<GetCase200ResponseSourceCaseDataSourceCauseOfActionArrayInner>",
            "format": ""
        },
        {
            "name": "sourceCaseStatus",
            "baseName": "sourceCaseStatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourcePageData",
            "baseName": "sourcePageData",
            "type": "Array<GetCase200ResponseSourceCaseDataSourcePageDataInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCase200ResponseSourceCaseData.attributeTypeMap;
    }

    public constructor() {
    }
}

