/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Count of each entitiy of a case is mentioned here so that you can calculate the number of requests needs to be done to obtain each entity results completely.
*/
export class GetCase200ResponseCaseStats {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * Count of number of parties available in the case being requested for.
    */
    'partyCount': number;
    /**
    * Count of number of attornies available in the case being requested for.
    */
    'attorneyCount': number;
    /**
    * Count of number of judges available in the case being requested for.
    */
    'judgeCount': number;
    /**
    * Count of number of docket entries available in the case being requested for.
    */
    'docketEntryCount': number;
    /**
    * Count of number of free documents available in the case being requested for.
    */
    'freeCaseDocumentCount': number;
    /**
    * Count of number of paid documents available in the case being requested for.
    */
    'paidCaseDocumentCount': number;
    /**
    * Count which includes the freeCaseDocumentCount and paidCaseDocumentCount.
    */
    'allCaseDocumentCount': number;
    /**
    * Count of number of documents that are available in the UniCourt CrowdSourced Library for the case being requested for.
    */
    'caseDocumentInLibraryCount': number;
    /**
    * Count of number of hearings available in the case being requested for.
    */
    'hearingCount': number;
    /**
    * Count of related cases that are available in the case being requested.
    */
    'relatedCaseCount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "partyCount",
            "baseName": "partyCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "attorneyCount",
            "baseName": "attorneyCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "judgeCount",
            "baseName": "judgeCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "docketEntryCount",
            "baseName": "docketEntryCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "freeCaseDocumentCount",
            "baseName": "freeCaseDocumentCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "paidCaseDocumentCount",
            "baseName": "paidCaseDocumentCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "allCaseDocumentCount",
            "baseName": "allCaseDocumentCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "caseDocumentInLibraryCount",
            "baseName": "caseDocumentInLibraryCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "hearingCount",
            "baseName": "hearingCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "relatedCaseCount",
            "baseName": "relatedCaseCount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCase200ResponseCaseStats.attributeTypeMap;
    }

    public constructor() {
    }
}

