/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceDataRawOrderedDataArrayInnerChildArrayInner } from '../models/GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceDataRawOrderedDataArrayInnerChildArrayInner';
import { HttpFile } from '../http/http';

export class GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceDataRawOrderedDataArrayInner {
    /**
    * Any docket text that belongs to the main docket text is added in the child.
    */
    'childArray': Array<GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceDataRawOrderedDataArrayInnerChildArrayInner>;
    /**
    * Label of the docket from the source.
    */
    'lbl': string | null;
    /**
    * Structure order
    */
    'ord': number;
    /**
    * List of available addresses.
    */
    'val': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "childArray",
            "baseName": "childArray",
            "type": "Array<GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceDataRawOrderedDataArrayInnerChildArrayInner>",
            "format": ""
        },
        {
            "name": "lbl",
            "baseName": "lbl",
            "type": "string",
            "format": ""
        },
        {
            "name": "ord",
            "baseName": "ord",
            "type": "number",
            "format": ""
        },
        {
            "name": "val",
            "baseName": "val",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceDataRawOrderedDataArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

