/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceData } from '../models/GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceData';
import { HttpFile } from '../http/http';

export class Hearing {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * Hearing Date
    */
    'hearingDate': Date;
    /**
    * Source Hearing Description Text
    */
    'hearingDescription': string | null;
    'hearingStructured': GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceData | null;
    /**
    * Location where the hearing will takeplace.
    */
    'location': string | null;
    /**
    * When this hearing was first fetched from the source.
    */
    'firstFetchDate': string;
    /**
    * When this hearing was last fetched from the source.
    */
    'lastFetchDate': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "hearingDate",
            "baseName": "hearingDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "hearingDescription",
            "baseName": "hearingDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "hearingStructured",
            "baseName": "hearingStructured",
            "type": "GetCase200ResponseSourceCaseDataSourcePageDataInnerAdditionalSourceData",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstFetchDate",
            "baseName": "firstFetchDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastFetchDate",
            "baseName": "lastFetchDate",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Hearing.attributeTypeMap;
    }

    public constructor() {
    }
}

