/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ImportPacerCaseByCourtUsingCaseNumber200ResponsePacerImportCaseResultsArrayInner } from '../models/ImportPacerCaseByCourtUsingCaseNumber200ResponsePacerImportCaseResultsArrayInner';
import { HttpFile } from '../http/http';

export class ImportPacerCaseByCourtUsingCaseNumber200Response {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * Court Fee charged for the Find Case request. This is only applicable for Appeal Cases.
    */
    'courtFee': number | null;
    'pacerImportCaseResultsArray': Array<ImportPacerCaseByCourtUsingCaseNumber200ResponsePacerImportCaseResultsArrayInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "courtFee",
            "baseName": "courtFee",
            "type": "number",
            "format": ""
        },
        {
            "name": "pacerImportCaseResultsArray",
            "baseName": "pacerImportCaseResultsArray",
            "type": "Array<ImportPacerCaseByCourtUsingCaseNumber200ResponsePacerImportCaseResultsArrayInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ImportPacerCaseByCourtUsingCaseNumber200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

