/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MatchedObject {
    'object': string;
    'matchedObjectId': string;
    'matchedObjectName': string;
    'matchedObjectAttribute': string;
    'highlightSnippet': string;
    'matchedObjectAPI': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "matchedObjectId",
            "baseName": "matchedObjectId",
            "type": "string",
            "format": ""
        },
        {
            "name": "matchedObjectName",
            "baseName": "matchedObjectName",
            "type": "string",
            "format": ""
        },
        {
            "name": "matchedObjectAttribute",
            "baseName": "matchedObjectAttribute",
            "type": "string",
            "format": ""
        },
        {
            "name": "highlightSnippet",
            "baseName": "highlightSnippet",
            "type": "string",
            "format": ""
        },
        {
            "name": "matchedObjectAPI",
            "baseName": "matchedObjectAPI",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return MatchedObject.attributeTypeMap;
    }

    public constructor() {
    }
}

