/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* American Bar Association (ABA) Rating of the Judge.
*/
export class NormJudgePublicData1AbaRatings {
    /**
    * rating
    */
    'rating': string | null;
    /**
    * Year when Rating was recieved.
    */
    'year': number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rating",
            "baseName": "rating",
            "type": "string",
            "format": ""
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NormJudgePublicData1AbaRatings.attributeTypeMap;
    }

    public constructor() {
    }
}

