/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class NormJudgePublicData1EducationArrayInner {
    /**
    * The Degree Awarded to the Judge
    */
    'degree': string | null;
    /**
    * The year when the degree was awarded.
    */
    'year': number | null;
    /**
    * The University which awarded the degree to the Judge.
    */
    'school': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "degree",
            "baseName": "degree",
            "type": "string",
            "format": ""
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number",
            "format": ""
        },
        {
            "name": "school",
            "baseName": "school",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NormJudgePublicData1EducationArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

