/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetCase200ResponsePartiesPartyArrayInnerContact } from '../models/GetCase200ResponsePartiesPartyArrayInnerContact';
import { NormJudgePublicData1AbaRatings } from '../models/NormJudgePublicData1AbaRatings';
import { NormJudgePublicData1Bio } from '../models/NormJudgePublicData1Bio';
import { NormJudgePublicData1EducationArrayInner } from '../models/NormJudgePublicData1EducationArrayInner';
import { NormJudgePublicData1JudicialSource } from '../models/NormJudgePublicData1JudicialSource';
import { NormJudgePublicData1NameHistoryArrayInner } from '../models/NormJudgePublicData1NameHistoryArrayInner';
import { ServiceHistory1 } from '../models/ServiceHistory1';
import { HttpFile } from '../http/http';

/**
* This contains the Judge Public details that is obtained from various sources.
*/
export class NormJudgePublicData1 {
    'object': string;
    /**
    * The judicial status of the Judge
    */
    'judicialStatus': string | null;
    'judicialSource': NormJudgePublicData1JudicialSource;
    'abaRatings': NormJudgePublicData1AbaRatings | null;
    /**
    * Other Names of the Judge.
    */
    'aliasArray': Array<string>;
    'bio': NormJudgePublicData1Bio;
    'contact': GetCase200ResponsePartiesPartyArrayInnerContact;
    /**
    * The Education History of the judge.
    */
    'educationArray': Array<NormJudgePublicData1EducationArrayInner>;
    /**
    * The non-judicial career history of the judge.
    */
    'professionalCareerArray': Array<string>;
    /**
    * Judicial History of the Judge.
    */
    'serviceHistoryArray': Array<ServiceHistory1>;
    /**
    * Name changes of the Judge. Change in the official name. Other names go to Alias array.
    */
    'nameHistoryArray': Array<NormJudgePublicData1NameHistoryArrayInner>;
    'firstFetchDate': Date | null;
    'lastFetchDate': Date | null;
    /**
    * Last Fetch Date of the Judge Update.
    */
    'lastFetchDateWithUpdates': Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "judicialStatus",
            "baseName": "judicialStatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "judicialSource",
            "baseName": "judicialSource",
            "type": "NormJudgePublicData1JudicialSource",
            "format": ""
        },
        {
            "name": "abaRatings",
            "baseName": "abaRatings",
            "type": "NormJudgePublicData1AbaRatings",
            "format": ""
        },
        {
            "name": "aliasArray",
            "baseName": "aliasArray",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "bio",
            "baseName": "bio",
            "type": "NormJudgePublicData1Bio",
            "format": ""
        },
        {
            "name": "contact",
            "baseName": "contact",
            "type": "GetCase200ResponsePartiesPartyArrayInnerContact",
            "format": ""
        },
        {
            "name": "educationArray",
            "baseName": "educationArray",
            "type": "Array<NormJudgePublicData1EducationArrayInner>",
            "format": ""
        },
        {
            "name": "professionalCareerArray",
            "baseName": "professionalCareerArray",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "serviceHistoryArray",
            "baseName": "serviceHistoryArray",
            "type": "Array<ServiceHistory1>",
            "format": ""
        },
        {
            "name": "nameHistoryArray",
            "baseName": "nameHistoryArray",
            "type": "Array<NormJudgePublicData1NameHistoryArrayInner>",
            "format": ""
        },
        {
            "name": "firstFetchDate",
            "baseName": "firstFetchDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastFetchDate",
            "baseName": "lastFetchDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastFetchDateWithUpdates",
            "baseName": "lastFetchDateWithUpdates",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return NormJudgePublicData1.attributeTypeMap;
    }

    public constructor() {
    }
}

