/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchNormalizedAttorneys200ResponseNormAttorneySearchResultArrayInner } from '../models/SearchNormalizedAttorneys200ResponseNormAttorneySearchResultArrayInner';
import { HttpFile } from '../http/http';

export class NormAttorneySearchResponse {
    'object': string;
    'normAttorneySearchResultArray': Array<SearchNormalizedAttorneys200ResponseNormAttorneySearchResultArrayInner>;
    /**
    * Query been sent by client
    */
    'q': string;
    /**
    * Query been sent by client
    */
    'normAttorneySearchId': string;
    /**
    * Link to next page.
    */
    'nextPageAPI': string | null;
    /**
    * Link to previous page.
    */
    'previousPageAPI': string | null;
    'pageNumber': number;
    /**
    * Total pages for matches that were found in the index.
    */
    'totalPages': number;
    /**
    * The number of matches that were found in the index.
    */
    'totalCount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "normAttorneySearchResultArray",
            "baseName": "normAttorneySearchResultArray",
            "type": "Array<SearchNormalizedAttorneys200ResponseNormAttorneySearchResultArrayInner>",
            "format": ""
        },
        {
            "name": "q",
            "baseName": "q",
            "type": "string",
            "format": ""
        },
        {
            "name": "normAttorneySearchId",
            "baseName": "normAttorneySearchId",
            "type": "string",
            "format": ""
        },
        {
            "name": "nextPageAPI",
            "baseName": "nextPageAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "previousPageAPI",
            "baseName": "previousPageAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "pageNumber",
            "baseName": "pageNumber",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalPages",
            "baseName": "totalPages",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NormAttorneySearchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

