/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The judicial source of the Judge
*/
export class NormJudgePublicData1JudicialSource {
    /**
    * Name of the Judicial Data Source
    */
    'name': string;
    /**
    * Type of acquisition of the data source
    */
    'type': NormJudgePublicData1JudicialSourceTypeEnum;
    /**
    * URL of the data source, if type is Website
    */
    'url': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "NormJudgePublicData1JudicialSourceTypeEnum",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NormJudgePublicData1JudicialSource.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum NormJudgePublicData1JudicialSourceTypeEnum {
    Website = 'Website',
    Other = 'Other'
}

