/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CaseAnalyticsAPI1 } from '../models/CaseAnalyticsAPI1';
import { Individual } from '../models/Individual';
import { NormOrganization1 } from '../models/NormOrganization1';
import { PartyAnalyticsAPI1 } from '../models/PartyAnalyticsAPI1';
import { RelatedNormParty1 } from '../models/RelatedNormParty1';
import { HttpFile } from '../http/http';

/**
* Norm Party
*/
export class NormParty {
    'object': string;
    'normPartyId': string;
    'name': string;
    'partyClassificationType': NormPartyPartyClassificationTypeEnum;
    'caseSearchAPI': string;
    'caseAnalyticsAPI': CaseAnalyticsAPI1;
    'individualData': Individual | null;
    'normOrganizationData': NormOrganization1;
    'partyAnalyticsAPI': PartyAnalyticsAPI1;
    'relatedNormPartyArray': Array<RelatedNormParty1>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "normPartyId",
            "baseName": "normPartyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "partyClassificationType",
            "baseName": "partyClassificationType",
            "type": "NormPartyPartyClassificationTypeEnum",
            "format": ""
        },
        {
            "name": "caseSearchAPI",
            "baseName": "caseSearchAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseAnalyticsAPI",
            "baseName": "caseAnalyticsAPI",
            "type": "CaseAnalyticsAPI1",
            "format": ""
        },
        {
            "name": "individualData",
            "baseName": "individualData",
            "type": "Individual",
            "format": ""
        },
        {
            "name": "normOrganizationData",
            "baseName": "normOrganizationData",
            "type": "NormOrganization1",
            "format": ""
        },
        {
            "name": "partyAnalyticsAPI",
            "baseName": "partyAnalyticsAPI",
            "type": "PartyAnalyticsAPI1",
            "format": ""
        },
        {
            "name": "relatedNormPartyArray",
            "baseName": "relatedNormPartyArray",
            "type": "Array<RelatedNormParty1>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NormParty.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum NormPartyPartyClassificationTypeEnum {
    Individual = 'Individual',
    Organization = 'Organization'
}

