/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class NormJudgePublicData1Bio {
    /**
    * Ethnic Group of the Judge.
    */
    'ethnicity': string | null;
    /**
    * The Birth City of the Judge.
    */
    'birthCity': string | null;
    /**
    * The Date of Birth of the Judge.
    */
    'birthDate': Date | null;
    /**
    * The Birth State of the Judge.
    */
    'birthState': string | null;
    /**
    * The Death City of the Judge.
    */
    'deathCity': string | null;
    /**
    * The Date of the Death of the Judge.
    */
    'deathDate': Date | null;
    /**
    * The Death State of the Judge.
    */
    'deathState': string | null;
    /**
    * The Political Affiliation of the Judge.
    */
    'politicalAffiliation': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ethnicity",
            "baseName": "ethnicity",
            "type": "string",
            "format": ""
        },
        {
            "name": "birthCity",
            "baseName": "birthCity",
            "type": "string",
            "format": ""
        },
        {
            "name": "birthDate",
            "baseName": "birthDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "birthState",
            "baseName": "birthState",
            "type": "string",
            "format": ""
        },
        {
            "name": "deathCity",
            "baseName": "deathCity",
            "type": "string",
            "format": ""
        },
        {
            "name": "deathDate",
            "baseName": "deathDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deathState",
            "baseName": "deathState",
            "type": "string",
            "format": ""
        },
        {
            "name": "politicalAffiliation",
            "baseName": "politicalAffiliation",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NormJudgePublicData1Bio.attributeTypeMap;
    }

    public constructor() {
    }
}

