/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CaseAnalyticsAPI1 } from '../models/CaseAnalyticsAPI1';
import { LawFirmAnalyticsAPI1 } from '../models/LawFirmAnalyticsAPI1';
import { NormOrganization1 } from '../models/NormOrganization1';
import { HttpFile } from '../http/http';

/**
* Schema for Norm Law Firm containing Organization sub-field.
*/
export class NormLawFirm1 {
    'object': string;
    'normLawFirmId': string;
    'name': string;
    'caseSearchAPI': string;
    'caseAnalyticsAPI': CaseAnalyticsAPI1;
    'normOrganizationData': NormOrganization1;
    'lawFirmAnalyticsAPI': LawFirmAnalyticsAPI1;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "normLawFirmId",
            "baseName": "normLawFirmId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseSearchAPI",
            "baseName": "caseSearchAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseAnalyticsAPI",
            "baseName": "caseAnalyticsAPI",
            "type": "CaseAnalyticsAPI1",
            "format": ""
        },
        {
            "name": "normOrganizationData",
            "baseName": "normOrganizationData",
            "type": "NormOrganization1",
            "format": ""
        },
        {
            "name": "lawFirmAnalyticsAPI",
            "baseName": "lawFirmAnalyticsAPI",
            "type": "LawFirmAnalyticsAPI1",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NormLawFirm1.attributeTypeMap;
    }

    public constructor() {
    }
}

