/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderCaseDocumentRequestPacerOptions } from '../models/OrderCaseDocumentRequestPacerOptions';
import { HttpFile } from '../http/http';

export class OrderCaseDocumentRequest {
    /**
    * Document ID which you want to order.
    */
    'caseDocumentId': string;
    /**
    * Flag value to determine if the document order is a preview order or no.
    */
    'isPreviewOnly': boolean;
    'pacerOptions'?: OrderCaseDocumentRequestPacerOptions;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "caseDocumentId",
            "baseName": "caseDocumentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPreviewOnly",
            "baseName": "isPreviewOnly",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "pacerOptions",
            "baseName": "pacerOptions",
            "type": "OrderCaseDocumentRequestPacerOptions",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderCaseDocumentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

