/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerSearchResultsArrayInnerPacerContent } from '../models/AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerSearchResultsArrayInnerPacerContent';
import { HttpFile } from '../http/http';

export class PACERPartySearchContent {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * Link to case in the case management/electronic case files (CM/ECF) system at the court.
    */
    'pclJurisdictionType': PACERPartySearchContentPclJurisdictionTypeEnum | null;
    /**
    * Sequentially generated number that identifies the case.
    */
    'pclCaseId': number;
    /**
    * Case Number.
    */
    'pclCaseNumberFull': string | null;
    /**
    * Title of the case.
    */
    'pclCaseTitle': string | null;
    /**
    * The divisional office in which the case was filed.
    */
    'pclCaseOffice': string | null;
    /**
    * The sequence number of the case.
    */
    'pclCaseNumber': number;
    /**
    * Code that identifies the type of case.
    */
    'pclCaseType': string | null;
    /**
    * The year in which the case falls. Could be two or four digit.
    */
    'pclCaseYear': number;
    /**
    * The general geographical region or specific court district. The court ID is the abbreviation of the court location combined with the court type (dc or bk). Please refer the Appendix B
    */
    'pclCourtId': string | null;
    /**
    * Filing date of the case.
    */
    'pclDateFiled': string | null;
    /**
    * This parameter represents the last name of the case when it is present
    */
    'pclLastName': string | null;
    /**
    * This parameter represents the first name of the case when it is present
    */
    'pclFirstName': string | null;
    /**
    * This parameter represents the middle name of the case when it is present
    */
    'pclMiddleName': string | null;
    /**
    * This parameter represents the generation of the case when it is present
    */
    'pclGeneration': string | null;
    /**
    * This parameter represents the party role of the case when it is present
    */
    'pclPartyRole': string | null;
    /**
    * This parameter represents the party type of the case when it is present
    */
    'pclPartyType': string | null;
    'pclCourtCase': AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerSearchResultsArrayInnerPacerContent;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclJurisdictionType",
            "baseName": "pclJurisdictionType",
            "type": "PACERPartySearchContentPclJurisdictionTypeEnum",
            "format": ""
        },
        {
            "name": "pclCaseId",
            "baseName": "pclCaseId",
            "type": "number",
            "format": ""
        },
        {
            "name": "pclCaseNumberFull",
            "baseName": "pclCaseNumberFull",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclCaseTitle",
            "baseName": "pclCaseTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclCaseOffice",
            "baseName": "pclCaseOffice",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclCaseNumber",
            "baseName": "pclCaseNumber",
            "type": "number",
            "format": ""
        },
        {
            "name": "pclCaseType",
            "baseName": "pclCaseType",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclCaseYear",
            "baseName": "pclCaseYear",
            "type": "number",
            "format": ""
        },
        {
            "name": "pclCourtId",
            "baseName": "pclCourtId",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclDateFiled",
            "baseName": "pclDateFiled",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclLastName",
            "baseName": "pclLastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclFirstName",
            "baseName": "pclFirstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclMiddleName",
            "baseName": "pclMiddleName",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclGeneration",
            "baseName": "pclGeneration",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclPartyRole",
            "baseName": "pclPartyRole",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclPartyType",
            "baseName": "pclPartyType",
            "type": "string",
            "format": ""
        },
        {
            "name": "pclCourtCase",
            "baseName": "pclCourtCase",
            "type": "AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerSearchResultsArrayInnerPacerContent",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PACERPartySearchContent.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PACERPartySearchContentPclJurisdictionTypeEnum {
    Appellate = 'Appellate',
    Bankruptcy = 'Bankruptcy',
    Criminal = 'Criminal',
    Civil = 'Civil',
    MultiDistrictLitigation = 'Multi-district Litigation',
    Null = 'null'
}

