/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerPageInfo } from '../models/AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerPageInfo';
import { AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerReceipt } from '../models/AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerReceipt';
import { AllCourtsPacerCaseLocatorPartySearch200ResponsePacerSearchResultsArrayInner } from '../models/AllCourtsPacerCaseLocatorPartySearch200ResponsePacerSearchResultsArrayInner';
import { HttpFile } from '../http/http';

export class PCLParty {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * Page number for which results where obtained.
    */
    'pageNumber': number;
    'pacerReceipt': AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerReceipt;
    'pacerPageInfo': AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerPageInfo;
    'pacerSearchResultsArray': Array<AllCourtsPacerCaseLocatorPartySearch200ResponsePacerSearchResultsArrayInner>;
    /**
    * Link to next page of the PCL Search Results.
    */
    'nextPageAPI': string | null;
    /**
    * Total number of pages to obtain all the objects the current PCL Search.
    */
    'totalPages': number;
    /**
    * Total number of records available for this Search.
    */
    'totalCount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "pageNumber",
            "baseName": "pageNumber",
            "type": "number",
            "format": ""
        },
        {
            "name": "pacerReceipt",
            "baseName": "pacerReceipt",
            "type": "AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerReceipt",
            "format": ""
        },
        {
            "name": "pacerPageInfo",
            "baseName": "pacerPageInfo",
            "type": "AllCourtsPacerCaseLocatorCaseSearch200ResponsePacerPageInfo",
            "format": ""
        },
        {
            "name": "pacerSearchResultsArray",
            "baseName": "pacerSearchResultsArray",
            "type": "Array<AllCourtsPacerCaseLocatorPartySearch200ResponsePacerSearchResultsArrayInner>",
            "format": ""
        },
        {
            "name": "nextPageAPI",
            "baseName": "nextPageAPI",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalPages",
            "baseName": "totalPages",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PCLParty.attributeTypeMap;
    }

    public constructor() {
    }
}

