/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PossibleNormParty1ScoreConstituents {
    'nameSimilarityScore': number;
    'otherPotentialNormParties': number;
    'secretaryOfStateId': PossibleNormParty1ScoreConstituentsSecretaryOfStateIdEnum;
    'address': PossibleNormParty1ScoreConstituentsAddressEnum;
    'email': PossibleNormParty1ScoreConstituentsEmailEnum;
    'phone': PossibleNormParty1ScoreConstituentsPhoneEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nameSimilarityScore",
            "baseName": "nameSimilarityScore",
            "type": "number",
            "format": "float"
        },
        {
            "name": "otherPotentialNormParties",
            "baseName": "otherPotentialNormParties",
            "type": "number",
            "format": ""
        },
        {
            "name": "secretaryOfStateId",
            "baseName": "secretaryOfStateId",
            "type": "PossibleNormParty1ScoreConstituentsSecretaryOfStateIdEnum",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "PossibleNormParty1ScoreConstituentsAddressEnum",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "PossibleNormParty1ScoreConstituentsEmailEnum",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "PossibleNormParty1ScoreConstituentsPhoneEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PossibleNormParty1ScoreConstituents.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PossibleNormParty1ScoreConstituentsSecretaryOfStateIdEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormParty1ScoreConstituentsAddressEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormParty1ScoreConstituentsEmailEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormParty1ScoreConstituentsPhoneEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}

