/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PossibleNormJudge1ScoreConstituents {
    'nameSimilarityScore': number;
    'otherPotentialNormJudges': number;
    'address': PossibleNormJudge1ScoreConstituentsAddressEnum;
    'email': PossibleNormJudge1ScoreConstituentsEmailEnum;
    'phone': PossibleNormJudge1ScoreConstituentsPhoneEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nameSimilarityScore",
            "baseName": "nameSimilarityScore",
            "type": "number",
            "format": "float"
        },
        {
            "name": "otherPotentialNormJudges",
            "baseName": "otherPotentialNormJudges",
            "type": "number",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "PossibleNormJudge1ScoreConstituentsAddressEnum",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "PossibleNormJudge1ScoreConstituentsEmailEnum",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "PossibleNormJudge1ScoreConstituentsPhoneEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PossibleNormJudge1ScoreConstituents.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PossibleNormJudge1ScoreConstituentsAddressEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormJudge1ScoreConstituentsEmailEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormJudge1ScoreConstituentsPhoneEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}

