/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PossibleNormLawFirm1SourceDetails {
    'source': PossibleNormLawFirm1SourceDetailsSourceEnum | null;
    'linkedNormAttorneyIdArray': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "source",
            "baseName": "source",
            "type": "PossibleNormLawFirm1SourceDetailsSourceEnum",
            "format": ""
        },
        {
            "name": "linkedNormAttorneyIdArray",
            "baseName": "linkedNormAttorneyIdArray",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PossibleNormLawFirm1SourceDetails.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PossibleNormLawFirm1SourceDetailsSourceEnum {
    LinkedInOtherCases = 'Case_Attorney_Linked_In_Other_Cases',
    FieldContainsLawFirm = 'Case_Attorney_Field_Contains_Law_Firm'
}

