/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PossibleNormLawFirm1ScoreConstituents {
    'nameSimilarityScore': number;
    'otherPotentialNormLawFirms': number;
    'secretaryOfStateId': PossibleNormLawFirm1ScoreConstituentsSecretaryOfStateIdEnum;
    'address': PossibleNormLawFirm1ScoreConstituentsAddressEnum;
    'email': PossibleNormLawFirm1ScoreConstituentsEmailEnum;
    'phone': PossibleNormLawFirm1ScoreConstituentsPhoneEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nameSimilarityScore",
            "baseName": "nameSimilarityScore",
            "type": "number",
            "format": "float"
        },
        {
            "name": "otherPotentialNormLawFirms",
            "baseName": "otherPotentialNormLawFirms",
            "type": "number",
            "format": ""
        },
        {
            "name": "secretaryOfStateId",
            "baseName": "secretaryOfStateId",
            "type": "PossibleNormLawFirm1ScoreConstituentsSecretaryOfStateIdEnum",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "PossibleNormLawFirm1ScoreConstituentsAddressEnum",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "PossibleNormLawFirm1ScoreConstituentsEmailEnum",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "PossibleNormLawFirm1ScoreConstituentsPhoneEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PossibleNormLawFirm1ScoreConstituents.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PossibleNormLawFirm1ScoreConstituentsSecretaryOfStateIdEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormLawFirm1ScoreConstituentsAddressEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormLawFirm1ScoreConstituentsEmailEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormLawFirm1ScoreConstituentsPhoneEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}

