/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PossibleNormLawFirm1ScoreConstituents } from '../models/PossibleNormLawFirm1ScoreConstituents';
import { PossibleNormLawFirm1SourceDetails } from '../models/PossibleNormLawFirm1SourceDetails';
import { HttpFile } from '../http/http';

export class PossibleNormLawFirm {
    /**
    * Name of the object
    */
    'object': string;
    'normLawFirmId': string;
    'normLawFirmName': string;
    'bestMatch': boolean;
    'sourceDetails': PossibleNormLawFirm1SourceDetails;
    'confidenceScore': number;
    'scoreConstituents': PossibleNormLawFirm1ScoreConstituents;
    'normLawFirmAPI': string;
    'associatedNormAttorneyAPI': string;
    'associatedNormJudgeAPI': string;
    'associatedNormPartiesAPI': string;
    'caseCountAnalyticsByNormLawFirmAPI': string;
    'caseCountAnalyticsByOpposingNormLawFirmAPI': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "normLawFirmId",
            "baseName": "normLawFirmId",
            "type": "string",
            "format": ""
        },
        {
            "name": "normLawFirmName",
            "baseName": "normLawFirmName",
            "type": "string",
            "format": ""
        },
        {
            "name": "bestMatch",
            "baseName": "bestMatch",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sourceDetails",
            "baseName": "sourceDetails",
            "type": "PossibleNormLawFirm1SourceDetails",
            "format": ""
        },
        {
            "name": "confidenceScore",
            "baseName": "confidenceScore",
            "type": "number",
            "format": "float"
        },
        {
            "name": "scoreConstituents",
            "baseName": "scoreConstituents",
            "type": "PossibleNormLawFirm1ScoreConstituents",
            "format": ""
        },
        {
            "name": "normLawFirmAPI",
            "baseName": "normLawFirmAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "associatedNormAttorneyAPI",
            "baseName": "associatedNormAttorneyAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "associatedNormJudgeAPI",
            "baseName": "associatedNormJudgeAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "associatedNormPartiesAPI",
            "baseName": "associatedNormPartiesAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByNormLawFirmAPI",
            "baseName": "caseCountAnalyticsByNormLawFirmAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "caseCountAnalyticsByOpposingNormLawFirmAPI",
            "baseName": "caseCountAnalyticsByOpposingNormLawFirmAPI",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return PossibleNormLawFirm.attributeTypeMap;
    }

    public constructor() {
    }
}

