/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PossibleNormAttorney1ScoreConstituents {
    'nameSimilarityScore': number;
    'otherPotentialNormAttorneys': number;
    'barId': PossibleNormAttorney1ScoreConstituentsBarIdEnum;
    'address': PossibleNormAttorney1ScoreConstituentsAddressEnum;
    'email': PossibleNormAttorney1ScoreConstituentsEmailEnum;
    'phone': PossibleNormAttorney1ScoreConstituentsPhoneEnum;
    'lawFirm': PossibleNormAttorney1ScoreConstituentsLawFirmEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nameSimilarityScore",
            "baseName": "nameSimilarityScore",
            "type": "number",
            "format": "float"
        },
        {
            "name": "otherPotentialNormAttorneys",
            "baseName": "otherPotentialNormAttorneys",
            "type": "number",
            "format": ""
        },
        {
            "name": "barId",
            "baseName": "barId",
            "type": "PossibleNormAttorney1ScoreConstituentsBarIdEnum",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "PossibleNormAttorney1ScoreConstituentsAddressEnum",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "PossibleNormAttorney1ScoreConstituentsEmailEnum",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "PossibleNormAttorney1ScoreConstituentsPhoneEnum",
            "format": ""
        },
        {
            "name": "lawFirm",
            "baseName": "lawFirm",
            "type": "PossibleNormAttorney1ScoreConstituentsLawFirmEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PossibleNormAttorney1ScoreConstituents.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PossibleNormAttorney1ScoreConstituentsBarIdEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormAttorney1ScoreConstituentsAddressEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormAttorney1ScoreConstituentsEmailEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormAttorney1ScoreConstituentsPhoneEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}
export enum PossibleNormAttorney1ScoreConstituentsLawFirmEnum {
    Matched = 'Matched',
    Mismatched = 'Mismatched',
    NotProvidedByDataSource = 'Not_Provided_By_Data_Source'
}

