/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetCourtsServiceStatus200ResponseCourtServiceStatusArrayInnerCaseUpdateServiceStatusServiceStatusDownDetails } from '../models/GetCourtsServiceStatus200ResponseCourtServiceStatusArrayInnerCaseUpdateServiceStatusServiceStatusDownDetails';
import { HttpFile } from '../http/http';

export class ServiceStatus {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * Status of Case Update Services Status.
    */
    'serviceUp': boolean;
    /**
    * Status Details of Case Update Services Status.
    */
    'serviceDetails': ServiceStatusServiceDetailsEnum;
    'serviceStatusDownDetails': GetCourtsServiceStatus200ResponseCourtServiceStatusArrayInnerCaseUpdateServiceStatusServiceStatusDownDetails | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceUp",
            "baseName": "serviceUp",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "serviceDetails",
            "baseName": "serviceDetails",
            "type": "ServiceStatusServiceDetailsEnum",
            "format": ""
        },
        {
            "name": "serviceStatusDownDetails",
            "baseName": "serviceStatusDownDetails",
            "type": "GetCourtsServiceStatus200ResponseCourtServiceStatusArrayInnerCaseUpdateServiceStatusServiceStatusDownDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ServiceStatus.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ServiceStatusServiceDetailsEnum {
    AcceptingCaseUpdates = 'acceptingCaseUpdates',
    NotAcceptingCaseUpdates = 'notAcceptingCaseUpdates',
    AcceptingCaseTrack = 'acceptingCaseTrack',
    NotAcceptingCaseTrack = 'notAcceptingCaseTrack',
    AcceptingAutoDocOrders = 'acceptingAutoDocOrders',
    AcceptingManualDocOrders = 'acceptingManualDocOrders',
    NotAcceptingAutoDocOrdersLimitExceeded = 'notAcceptingAutoDocOrdersLimitExceeded',
    NotAcceptingManualDocOrdersLimitExceeded = 'notAcceptingManualDocOrdersLimitExceeded',
    NotAcceptingDocOrders = 'notAcceptingDocOrders'
}

