/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A timeline of courts where the judge has been employed.
*/
export class ServiceHistory1 {
    'object': string;
    /**
    * The President-in-charge of the Judges appointment.
    */
    'appointedBy': string | null;
    /**
    * The reason for the Judges termination for the current position.
    */
    'reasonForTermination': string | null;
    /**
    * The court served by the Judge. The court is taken from source.
    */
    'sourceCourt': string | null;
    /**
    * Title held by the Judge.
    */
    'title': string | null;
    /**
    * The year in which the Judge began practicing in his current service.
    */
    'fromYear': number | null;
    /**
    * The year in which the Judge stoped practicing in his current service.
    */
    'toYear': number | null;
    /**
    * The year in which the Judge began practicing in his current service.
    */
    'fromDate': Date | null;
    /**
    * The year in which the Judge stoped practicing in his current service.
    */
    'toDate': Date | null;
    /**
    * Boolean indicating if the service history  is visible or not.
    */
    'isVisible': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "appointedBy",
            "baseName": "appointedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "reasonForTermination",
            "baseName": "reasonForTermination",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceCourt",
            "baseName": "sourceCourt",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromYear",
            "baseName": "fromYear",
            "type": "number",
            "format": ""
        },
        {
            "name": "toYear",
            "baseName": "toYear",
            "type": "number",
            "format": ""
        },
        {
            "name": "fromDate",
            "baseName": "fromDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "toDate",
            "baseName": "toDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isVisible",
            "baseName": "isVisible",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ServiceHistory1.attributeTypeMap;
    }

    public constructor() {
    }
}

