/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ServiceStatusDownDetails {
    /**
    * Name of the object
    */
    'object': string;
    /**
    * This field determines the reason behind status being down. Following are the possible reason for the service to be down:   underMaintenance: It means that the site is under scheduled maintenance.   notIntegrated: When an court with specific case type is not integrated in UniCourt.   brokenIntegration: Due to some updates made to the court site our existing Integration has broken and will require a fix to be made to support this court again for a spcific case type category.   sourceMigrated: When a source is migrated from one site to another for a specific case type category.
    */
    'reason': ServiceStatusDownDetailsReasonEnum;
    /**
    * Details of the reason.
    */
    'details': string | null;
    /**
    * Estimated Time this Service could be Up again for the use.
    */
    'eta': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "ServiceStatusDownDetailsReasonEnum",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string",
            "format": ""
        },
        {
            "name": "eta",
            "baseName": "eta",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ServiceStatusDownDetails.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ServiceStatusDownDetailsReasonEnum {
    UnderMaintenance = 'underMaintenance',
    NotIntegrated = 'notIntegrated',
    BrokenIntegration = 'brokenIntegration',
    SourceMigrated = 'sourceMigrated'
}

