/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BarRecordPreview1 } from '../models/BarRecordPreview1';
import { HttpFile } from '../http/http';

export class SimilarNormAttorney1 {
    'object': string;
    'normAttorneyId': string;
    'normAttorneyAPI': string;
    'name': string;
    'normAttorneySimilarityScore': number;
    'barRecordPreviewArray': Array<BarRecordPreview1>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "normAttorneyId",
            "baseName": "normAttorneyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "normAttorneyAPI",
            "baseName": "normAttorneyAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "normAttorneySimilarityScore",
            "baseName": "normAttorneySimilarityScore",
            "type": "number",
            "format": "float"
        },
        {
            "name": "barRecordPreviewArray",
            "baseName": "barRecordPreviewArray",
            "type": "Array<BarRecordPreview1>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimilarNormAttorney1.attributeTypeMap;
    }

    public constructor() {
    }
}

