/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SOSAssociatedNormOrganization1 {
    'object': string;
    'normOrganizationId': string | null;
    'normOrganizationAPI': string | null;
    'relationshipType': SOSAssociatedNormOrganization1RelationshipTypeEnum;
    'name': string;
    'fromDate': Date;
    'toDate': Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "normOrganizationId",
            "baseName": "normOrganizationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "normOrganizationAPI",
            "baseName": "normOrganizationAPI",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "relationshipType",
            "baseName": "relationshipType",
            "type": "SOSAssociatedNormOrganization1RelationshipTypeEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromDate",
            "baseName": "fromDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "toDate",
            "baseName": "toDate",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return SOSAssociatedNormOrganization1.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SOSAssociatedNormOrganization1RelationshipTypeEnum {
    Parent = 'Parent',
    Child = 'Child'
}

