/**
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateCaseRequestPacerOptionsAdditionalPageArrayInner {
    'page'?: UpdateCaseRequestPacerOptionsAdditionalPageArrayInnerPageEnum;
    /**
    * You can limit how often this page information is fetched to reduce your PACER fees.  Min days is 0 and Max days is 100.  Example: 1.  Specifying a value of 0 ensures that this page is fetched from PACER for this case update irrespective of when the page was last fetched. 2.  Specifying a value of 30 ensures that this page is fetched from PACER for this case update only if the last fetch was older than 30 days. 
    */
    'fetchIfOlderThanDays'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "page",
            "baseName": "page",
            "type": "UpdateCaseRequestPacerOptionsAdditionalPageArrayInnerPageEnum",
            "format": ""
        },
        {
            "name": "fetchIfOlderThanDays",
            "baseName": "fetchIfOlderThanDays",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateCaseRequestPacerOptionsAdditionalPageArrayInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UpdateCaseRequestPacerOptionsAdditionalPageArrayInnerPageEnum {
    AssociatedCases = 'associatedCases',
    CaseSummary = 'caseSummary',
    ListOfCreditors = 'listOfCreditors'
}

